### ISSUE TITLE
Suggestions: Player Growth and Regen

### ISSUE THREAD

**Issue by TheAwesomeGem** [pargsoft/_v2k4-Career-Mod#1]
Player Growth:
Mental stats (Positioning, Vision, Interceptions, Aggression, Composure) and Reactions (which is pretty much involved in calculating player ratings for all positions) barely have any growth...only Technical stats seem to grow the most on players, and that makes them unbalanced, which is a problem especially with Youth players. Would be nice to have that fixed.
There are also some unbalanced growth depending on player's position - few examples:CB's Sprint Speed often goes up to 90+ but their Acceleration stays the same or barely grow, CM's have a LOT of Finishing growth (often reaching 99) but little to none growth to defending stats(Tackling, Marking, Interceptions), Goalies have enormous GK Kicking growth but shit GK Positioning growth, and every position apart from GK's have shitty Reactions growth, as stated previously.

Regens (regenerated players of retiring players):
Many Regens often appear mispositioned e.g. regen strikers have the stats of wingers (high ball Control/Dribbling but bad Finishing/Positioning/Strength) and vice versa.

**Comment by pargsoft** [comment]
Although all these ideas are good. They are not on my radar right now and closing as old.
